/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        YoutubeAPIClient client = new YoutubeAPIClient();
            String videoID = "Atb5G2FNxwn8GbqE"; // Replace with a valid YouTube video ID
            String transcript = client.getTranscript(videoID);
            System.out.println(transcript);
        
    }
}
